# -*- coding: utf-8 -*-
"""딥러닝_케라스2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/KimJH9054/2819a4ae6f7717a9037e0448ee79ed8f/overview-of-colaboratory-features.ipynb
"""

class Engine:
    def __init__(self, horsepower):
        self.horsepower = horsepower

    def start(self):
        print(f"Engine started with {self.horsepower} horsepower.")

